INSERT INTO `SHIFT_MANAGER`.`UTENTI` (`UTENTE_ID`, `NOME`, `COGNOME`) VALUES ('', 'Luca', 'Mori');
INSERT INTO `SHIFT_MANAGER`.`UTENTI` (`NOME`, `COGNOME`) VALUES ('Daniel', 'Bonfanti');

INSERT INTO `SHIFT_MANAGER`.`CLIENTI` (`NOME`) VALUES ('MAZZONI');
INSERT INTO `SHIFT_MANAGER`.`CLIENTI` (`NOME`) VALUES ('RIBONI');
INSERT INTO `SHIFT_MANAGER`.`CLIENTI` (`NOME`) VALUES ('GIEMMEPI');
INSERT INTO `SHIFT_MANAGER`.`COMMESSE` (`NOME`,`CLIENTE_ID`)VALUES('FILIPPINE',1);
INSERT INTO `SHIFT_MANAGER`.`COMMESSE` (`NOME`,`CLIENTE_ID`)VALUES('SAPONE',1);
INSERT INTO `SHIFT_MANAGER`.`COMMESSE` (`NOME`,`CLIENTE_ID`)VALUES('TSUNE',2);
INSERT INTO `SHIFT_MANAGER`.`COMMESSE` (`NOME`,`CLIENTE_ID`)VALUES('SIEMENS',2);
INSERT INTO `SHIFT_MANAGER`.`COMMESSE` (`NOME`,`CLIENTE_ID`)VALUES('PELLE',3);
INSERT INTO `SHIFT_MANAGER`.`COMMESSE` (`NOME`,`CLIENTE_ID`)VALUES('STOFFA',3);
INSERT INTO `SHIFT_MANAGER`.`COMMESSE` (`NOME`,`CLIENTE_ID`)VALUES('PLASTICA',3);


INSERT INTO `SHIFT_MANAGER`.`RESOCONTO_LAVORO`
(`UTENTE_ID`,`DATA_INTERVENTO`,`TOTALE_LAVORO`,`TOTALE_VIAGGIO`,`SPESE`,`KM`,`TIPOLOGIA_LAVORO`,`COMMESSA_ID`,`CLIENTE_ID`) VALUES (1,NOW(),5,2,0,30,1,1,1);
INSERT INTO `SHIFT_MANAGER`.`RESOCONTO_LAVORO`
(`UTENTE_ID`,`DATA_INTERVENTO`,`TOTALE_LAVORO`,`TOTALE_VIAGGIO`,`SPESE`,`KM`,`TIPOLOGIA_LAVORO`,`COMMESSA_ID`,`CLIENTE_ID`) VALUES (1,NOW(),3,2,0,0,0,1,1);
INSERT INTO `SHIFT_MANAGER`.`RESOCONTO_LAVORO`
(`UTENTE_ID`,`DATA_INTERVENTO`,`TOTALE_LAVORO`,`TOTALE_VIAGGIO`,`SPESE`,`KM`,`TIPOLOGIA_LAVORO`,`COMMESSA_ID`,`CLIENTE_ID`) VALUES (2,NOW(),5,2,0,30,1,1,1);
INSERT INTO `SHIFT_MANAGER`.`RESOCONTO_LAVORO`
(`UTENTE_ID`,`DATA_INTERVENTO`,`TOTALE_LAVORO`,`TOTALE_VIAGGIO`,`SPESE`,`KM`,`TIPOLOGIA_LAVORO`,`COMMESSA_ID`,`CLIENTE_ID`) VALUES (2,NOW(),3,2,0,0,0,1,1);

INSERT INTO `SHIFT_MANAGER`.`RESOCONTO_LAVORO`
(`UTENTE_ID`,`DATA_INTERVENTO`,`TOTALE_LAVORO`,`TOTALE_VIAGGIO`,`SPESE`,`KM`,`TIPOLOGIA_LAVORO`,`COMMESSA_ID`,`CLIENTE_ID`) VALUES (1,NOW(),5,2,0,30,1,1,1);
INSERT INTO `SHIFT_MANAGER`.`RESOCONTO_LAVORO`
(`UTENTE_ID`,`DATA_INTERVENTO`,`TOTALE_LAVORO`,`TOTALE_VIAGGIO`,`SPESE`,`KM`,`TIPOLOGIA_LAVORO`,`COMMESSA_ID`,`CLIENTE_ID`) VALUES (1,NOW(),3,2,0,0,0,1,1);
INSERT INTO `SHIFT_MANAGER`.`RESOCONTO_LAVORO`
(`UTENTE_ID`,`DATA_INTERVENTO`,`TOTALE_LAVORO`,`TOTALE_VIAGGIO`,`SPESE`,`KM`,`TIPOLOGIA_LAVORO`,`COMMESSA_ID`,`CLIENTE_ID`) VALUES (2,NOW(),5,2,0,30,1,1,1);
INSERT INTO `SHIFT_MANAGER`.`RESOCONTO_LAVORO`
(`UTENTE_ID`,`DATA_INTERVENTO`,`TOTALE_LAVORO`,`TOTALE_VIAGGIO`,`SPESE`,`KM`,`TIPOLOGIA_LAVORO`,`COMMESSA_ID`,`CLIENTE_ID`) VALUES (2,NOW(),3,2,0,0,0,1,1);

select * from CLIENTI;
select * from COMMESSE;
select co.COMMESSA_ID, cl.NOME, co.NOME from COMMESSE co
JOIN CLIENTI cl ON cl.CLIENTE_ID = co.CLIENTE_ID;

select * from `SHIFT_MANAGER`.`RESOCONTO_LAVORO`;

/*
select * from SHIFT_MANAGER.UTENTI2RAPPORTINO u2r
JOIN RAPPORTINO r ON r.RAPPORTINO_ID = u2r.RAPPORTINO_ID
JOIN RESOCONTO_LAVORO l ON l.RAPPORTINO_ID = r.RAPPORTINO_ID
WHERE u2r.UTENTE_ID = 2;
